/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.view.form;

import client.listeners.ServerStoppedListener;
import client.view.controller.Controller;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author ANA
 */
public class FormMain extends javax.swing.JFrame {

    /**
     * Creates new form FormMain
     */
    public FormMain() {
        setLayout(new BorderLayout());
        setContentPane(new JLabel(new ImageIcon("resources/home_bg.png")));
        setLayout(new FlowLayout());
        initComponents();
        setLocationRelativeTo(null);

        addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
                try {
                    Controller.getInstance().logout();
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }

            @Override
            public void windowClosed(WindowEvent e) {
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });

        Controller.getInstance().setServerStoppedListener(new ServerStoppedListener() {
            @Override
            public void serverStopped() {
                stop();
            }
        });
    }

    public void stop() {
        JOptionPane.showMessageDialog(this, "Konekcija sa serverom je prekinuta. Molimo Vas, pokušajte kasnije.", "Prekid konekcije", JOptionPane.ERROR_MESSAGE);
        this.dispose();
        System.exit(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuProfile = new javax.swing.JMenu();
        jMenuItemProfileView = new javax.swing.JMenuItem();
        jMenuItemProfileChangePass = new javax.swing.JMenuItem();
        jMenuMedicines = new javax.swing.JMenu();
        jMenuItemMedicineView = new javax.swing.JMenuItem();
        jMenuOperations = new javax.swing.JMenu();
        jMenuItemOperationsView = new javax.swing.JMenuItem();
        jMenuInvoices = new javax.swing.JMenu();
        jMenuItemInvoicesNew = new javax.swing.JMenuItem();
        jMenuItemInvoicesView = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N

        jMenuProfile.setText("Profil");
        jMenuProfile.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N

        jMenuItemProfileView.setFont(new java.awt.Font("Lucida Fax", 0, 11)); // NOI18N
        jMenuItemProfileView.setText("Pregled");
        jMenuItemProfileView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProfileViewActionPerformed(evt);
            }
        });
        jMenuProfile.add(jMenuItemProfileView);

        jMenuItemProfileChangePass.setFont(new java.awt.Font("Lucida Fax", 0, 11)); // NOI18N
        jMenuItemProfileChangePass.setText("Promijeni šifru ");
        jMenuItemProfileChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProfileChangePassActionPerformed(evt);
            }
        });
        jMenuProfile.add(jMenuItemProfileChangePass);

        jMenuBar1.add(jMenuProfile);

        jMenuMedicines.setText("Lijekovi");
        jMenuMedicines.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N

        jMenuItemMedicineView.setFont(new java.awt.Font("Lucida Fax", 0, 11)); // NOI18N
        jMenuItemMedicineView.setText("Pregled");
        jMenuItemMedicineView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMedicineViewActionPerformed(evt);
            }
        });
        jMenuMedicines.add(jMenuItemMedicineView);

        jMenuBar1.add(jMenuMedicines);

        jMenuOperations.setText("Operacije");
        jMenuOperations.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N

        jMenuItemOperationsView.setFont(new java.awt.Font("Lucida Fax", 0, 11)); // NOI18N
        jMenuItemOperationsView.setText("Pregled");
        jMenuItemOperationsView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOperationsViewActionPerformed(evt);
            }
        });
        jMenuOperations.add(jMenuItemOperationsView);

        jMenuBar1.add(jMenuOperations);

        jMenuInvoices.setText("Racuni");
        jMenuInvoices.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N

        jMenuItemInvoicesNew.setFont(new java.awt.Font("Lucida Fax", 0, 11)); // NOI18N
        jMenuItemInvoicesNew.setText("Kreiraj novi");
        jMenuItemInvoicesNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInvoicesNewActionPerformed(evt);
            }
        });
        jMenuInvoices.add(jMenuItemInvoicesNew);

        jMenuItemInvoicesView.setFont(new java.awt.Font("Lucida Fax", 0, 11)); // NOI18N
        jMenuItemInvoicesView.setText("Pregled postojecih");
        jMenuItemInvoicesView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInvoicesViewActionPerformed(evt);
            }
        });
        jMenuInvoices.add(jMenuItemInvoicesView);

        jMenuBar1.add(jMenuInvoices);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemProfileViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProfileViewActionPerformed
        new FormProfile(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItemProfileViewActionPerformed

    private void jMenuItemProfileChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProfileChangePassActionPerformed
        new FormChangePassword(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItemProfileChangePassActionPerformed

    private void jMenuItemMedicineViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMedicineViewActionPerformed
        new FormMedicinesView(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItemMedicineViewActionPerformed

    private void jMenuItemOperationsViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOperationsViewActionPerformed
        new FormOperations(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItemOperationsViewActionPerformed

    private void jMenuItemInvoicesNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInvoicesNewActionPerformed
        new FormNewInvoice(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItemInvoicesNewActionPerformed

    private void jMenuItemInvoicesViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInvoicesViewActionPerformed
        new FormInvoicesView(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItemInvoicesViewActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuInvoices;
    private javax.swing.JMenuItem jMenuItemInvoicesNew;
    private javax.swing.JMenuItem jMenuItemInvoicesView;
    private javax.swing.JMenuItem jMenuItemMedicineView;
    private javax.swing.JMenuItem jMenuItemOperationsView;
    private javax.swing.JMenuItem jMenuItemProfileChangePass;
    private javax.swing.JMenuItem jMenuItemProfileView;
    private javax.swing.JMenu jMenuMedicines;
    private javax.swing.JMenu jMenuOperations;
    private javax.swing.JMenu jMenuProfile;
    // End of variables declaration//GEN-END:variables
}
