/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package server.view.form;

import commonlib.domain.Employee;
import java.awt.Color;
import java.io.IOException;
import java.util.LinkedList;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import server.listener.LoggingListener;
import server.threads.ServerThread;
import server.view.components.TableModelLoggedUsers;

/**
 *
 * @author ANA
 */
public class FormMain extends javax.swing.JFrame {

    private ServerThread serverThread;

    /**
     * Creates new form FormMain
     */
    public FormMain() {
        initComponents();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoggedEmployees = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        mbMainMenu = new javax.swing.JMenuBar();
        jMenuConfiguration = new javax.swing.JMenu();
        jMenuItemConfigurationDatabase = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server");

        btnStart.setBackground(new java.awt.Color(255, 255, 255));
        btnStart.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        btnStart.setText("Pokreni");
        btnStart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)));
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnStop.setBackground(new java.awt.Color(255, 255, 255));
        btnStop.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        btnStop.setText("Zaustavi");
        btnStop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        tblLoggedEmployees.setFont(new java.awt.Font("Lucida Fax", 0, 13)); // NOI18N
        tblLoggedEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblLoggedEmployees.setSelectionBackground(new java.awt.Color(255, 153, 153));
        jScrollPane1.setViewportView(tblLoggedEmployees);

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 0, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Prijavljeni korisnici");

        jMenuConfiguration.setText("Konfiguracija");
        jMenuConfiguration.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N

        jMenuItemConfigurationDatabase.setFont(new java.awt.Font("Lucida Fax", 0, 11)); // NOI18N
        jMenuItemConfigurationDatabase.setText("Konfiguracija baze podataka");
        jMenuConfiguration.add(jMenuItemConfigurationDatabase);

        mbMainMenu.add(jMenuConfiguration);

        setJMenuBar(mbMainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStop)
                    .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        if (serverThread == null || !serverThread.isAlive()) {
            try {
                serverThread = new ServerThread();
                serverThread.start();
                this.setTitle("Server (pokrenut)");
                serverThread.setLoggingListener(new LoggingListener() {
                    @Override
                    public void loginHappened(Employee employee) {
                        TableModelLoggedUsers model = (TableModelLoggedUsers) tblLoggedEmployees.getModel();
                        model.addEmployee(employee);
                    }

                    @Override
                    public void logoutHappened(Employee employee) {
                        TableModelLoggedUsers model = (TableModelLoggedUsers) tblLoggedEmployees.getModel();
                        model.removeEmployee(employee);
                    }
                });
                btnStart.setEnabled(false);
                btnStop.setEnabled(true);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        if (serverThread.getServerSocket() != null && serverThread.getServerSocket().isBound()) {
            try {
                serverThread.stopAllThreads();
                TableModelLoggedUsers model = (TableModelLoggedUsers) tblLoggedEmployees.getModel();
                model.updateTable(serverThread.getLoggedInEmployees());
                serverThread.getServerSocket().close();
                this.setTitle("Server");
                btnStart.setEnabled(true);
                btnStop.setEnabled(false);
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnStopActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenuConfiguration;
    private javax.swing.JMenuItem jMenuItemConfigurationDatabase;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar mbMainMenu;
    private javax.swing.JTable tblLoggedEmployees;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        btnStop.setEnabled(false);
        tblLoggedEmployees.setModel(new TableModelLoggedUsers(new LinkedList<>()));
        tblLoggedEmployees.getTableHeader().setOpaque(false);
        tblLoggedEmployees.getTableHeader().setBackground(new Color(51, 153, 255));
        tblLoggedEmployees.getTableHeader().setForeground(new Color(255, 255, 255));
        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) tblLoggedEmployees.getDefaultRenderer(Object.class);
        renderer.setHorizontalAlignment(JLabel.LEFT);
        tblLoggedEmployees.setRowHeight(22);
    }
}
